CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;

CREATE TABLE Customer (
cID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cnName VARCHAR(30) NOT NULL,
cAge TINYINT NOT NULL
);

CREATE TABLE O_rder(
oID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
cID  INT NOT NULL ,
oDate DATETIME,
oTotalPrice INT,
FOREIGN KEY (cID) REFERENCES Customer(cID)
);

CREATE TABLE  Product(
pID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
pName VARCHAR(30) NOT NULL,
pPrice INT NOT NULL 
);

CREATE TABLE OrderDetail (
oID INT NOT NULL ,
pID INT NOT NULL,
odQTY INT NOT NULL,
FOREIGN KEY (oID) REFERENCES O_rder(oID),
FOREIGN KEY (pID) REFERENCES Product(pID)
); 
